source 'https://cdn.cocoapods.org/'

platform :ios, '16.0'
inhibit_all_warnings!

target 'DogBreedGuessing' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DogBreedGuessing
  pod 'SDWebImage'

  target 'DogBreedGuessingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DogBreedGuessingUITests' do
    # Pods for testing
  end

end
